<?php
/**
 * Maxx
 * @category    Maxx
 * @package     Maxx_AgePopup
 * @copyright   Copyright (c) 2018 Maxx
 */
?>
<a id="agepopupButton" href="#agepopupContent" style="display: none;" title="Lorem ipsum dolor sit amet">Inline</a>
<div style="display: none;">
		<div id="agepopupContent" style="width:600px;height:150px;overflow:auto;">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Etiam quis mi eu elit tempor facilisis id et neque.
            vehicula non pretium varius, cursus ac tortor.
            Vivamus fringilla congue laoreet.
            Quisque ultrices sodales orci, quis rhoncus justo auctor in.
            Phasellus dui eros, bibendum eu feugiat ornare, faucibus eu mi.
            Nunc aliquet tempus sem, id aliquam diam varius ac.
            Maecenas nisl nunc, molestie vitae eleifend vel, iaculis sed magna.
		</div>
</div>
